.TH cubicweb\-ctl 1 "2008-01-14" cubicweb\-ctl
.SH NAME
.B cubicweb\-ctl
\- cubicweb control utility


.SH SYNOPSIS
.B  cubicweb-ctl <command>
[
.I OPTIONS
] [
.I <command arguments>
]

.SH DESCRIPTION
.PP
CubicWeb utility to create and control instances, and more generally do all
cubicweb's related tasks you can have to do using the command line. Available
commands will depends on which part of the framework are installed.
.PP
Type
.B "cubicweb\-ctl <command> \fB\-\-help\fR"
for more information about a specific command.

.SH COPYRIGHT 
Copyright (c) 2003-2008 LOGILAB S.A. (Paris, FRANCE).
http://www.logilab.fr/ -- mailto:contact@logilab.fr
