#! /bin/sh -e

if [ "$1" = configure ]; then
    # XXX bw compat: erudi -> cubicweb migration
    if [ -e "/usr/share/erudi/templates/" ]; then
      # skip the "shared" subdirectory by moving it first, restoring it later
      mv /usr/share/erudi/templates/shared /usr/share/erudi/
      mv /usr/share/erudi/templates/* /usr/share/cubicweb/cubes/
      mv /usr/share/erudi/shared /usr/share/erudi/templates
      echo 'moved /usr/share/erudi/templates/* to /usr/share/cubicweb/cubes/'
    fi
fi 
#DEBHELPER#
 
exit 0
